import "dotenv/config";

import { db } from "@/app/db";
import { companies, vehicles } from "../db/schema";
import { eq } from "drizzle-orm";

async function main() {
  console.log("🚀 Insertando vehículos...");

  // 1. Buscar empresa
  const empresa = await db.query.companies.findFirst({
    where: eq(companies.nombre, "TURISMO BUS UNIVERSO"),
  });

  if (!empresa) {
    throw new Error("❌ TURISMO BUS UNIVERSO no existe");
  }

  // 2. DATA TIPADA 🔥
  const data: (typeof vehicles.$inferInsert)[] = [
    // 🟢 BUSES
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "MERCEDES BENZ",
      modelo: "OF-1721/59",
      placa: "M1R969",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "5000.00",
      moneda: "USD",
      total: "5000.00",
      fecha_de_adquisicion: "2018-01-17",
      tipo_de_vehiculo: "Ómnibus Transporte Interprovincial",
      uso: "TRANSPORTE REGULAR DE PERSONAS",
    },
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "MERCEDES BENZ",
      modelo: "OF-1730/59",
      placa: "T5H955",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "11000.00",
      moneda: "SOL",
      total: "11000.00",
      fecha_de_adquisicion: "2019-10-11",
      tipo_de_vehiculo: "Ómnibus Transporte Interprovincial",
      uso: "TRANSPORTE REGULAR DE PERSONAS",
    },
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "SCANIA",
      modelo: "K124IB6X2NB380",
      placa: "A7V963",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "11000.00",
      moneda: "SOL",
      total: "11000.00",
      fecha_de_adquisicion: "2019-10-15",
      tipo_de_vehiculo: "Ómnibus Transporte Interprovincial",
      uso: "TRANSPORTE REGULAR DE PERSONAS",
    },
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "MERCEDES BENZ",
      modelo: "O-400 RSD",
      placa: "B4H955",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "10000.00",
      moneda: "SOL",
      total: "10000.00",
      fecha_de_adquisicion: "2019-09-11",
      tipo_de_vehiculo: "Ómnibus Transporte Interprovincial",
      uso: "TRANSPORTE REGULAR DE PERSONAS",
    },
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "MERCEDES BENZ",
      modelo: "OF-1721/59",
      placa: "T2H961",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "12000.00",
      moneda: "SOL",
      total: "12000.00",
      fecha_de_adquisicion: "2019-04-05",
      tipo_de_vehiculo: "Ómnibus Transporte Interprovincial",
      uso: "TRANSPORTE REGULAR DE PERSONAS",
    },
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "SCANIA",
      modelo: "K124IB8X2NB380",
      placa: "A1O964",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "11000.00",
      moneda: "SOL",
      total: "11000.00",
      fecha_de_adquisicion: "2016-09-12",
      tipo_de_vehiculo: "Ómnibus Transporte Interprovincial",
      uso: "TRANSPORTE REGULAR DE PERSONAS",
    },
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "MERCEDES BENZ",
      modelo: "OF-1721/59",
      placa: "T3C967",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "12000.00",
      moneda: "SOL",
      total: "12000.00",
      fecha_de_adquisicion: "2017-10-23",
      tipo_de_vehiculo: "Ómnibus Transporte de Personal",
      uso: "TRANSPORTE ESPECIAL DE PERSONAS – TRABAJADORES",
    },
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "MERCEDES BENZ",
      modelo: "OF-1730/59",
      placa: "F1U967",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "20000.00",
      moneda: "USD",
      total: "20000.00",
      fecha_de_adquisicion: "2023-08-11",
      tipo_de_vehiculo: "Ómnibus Transporte Interprovincial",
      uso: "TRANSPORTE REGULAR DE PERSONAS",
    },
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "MERCEDES BENZ",
      modelo: "OF-1730/59",
      placa: "T5N953",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "12000.00",
      moneda: "SOL",
      total: "12000.00",
      fecha_de_adquisicion: "2020-03-11",
      tipo_de_vehiculo: "Ómnibus Transporte de Personal",
      uso: "TRANSPORTE ESPECIAL DE PERSONAS – TRABAJADORES",
    },
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "MERCEDES BENZ",
      modelo: "OF-1730/59",
      placa: "C2M964",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "18000.00",
      moneda: "SOL",
      total: "18000.00",
      fecha_de_adquisicion: "2021-08-06",
      tipo_de_vehiculo: "Ómnibus Transporte Interprovincial",
      uso: "TRANSPORTE REGULAR DE PERSONAS",
    },
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "MERCEDES BENZ",
      modelo: "OF-1730/59",
      placa: "C9I955",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "5000.00",
      moneda: "USD",
      total: "5000.00",
      fecha_de_adquisicion: "2023-10-20",
      tipo_de_vehiculo: "Ómnibus Transporte de Personal",
      uso: "TRANSPORTE ESPECIAL DE PERSONAS – TRABAJADORES",
    },
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "MERCEDES BENZ",
      modelo: "OF-1730/59",
      placa: "D3N950",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "130900.00",
      moneda: "SOL",
      total: "130900.00",
      fecha_de_adquisicion: "2023-01-30",
      tipo_de_vehiculo: "Ómnibus Transporte de Personal",
      uso: "TRANSPORTE ESPECIAL DE PERSONAS – TRABAJADORES",
    },
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "MERCEDES BENZ",
      modelo: "OF-1721/59",
      placa: "T1F968",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "10000.00",
      moneda: "SOL",
      total: "10000.00",
      fecha_de_adquisicion: "2025-01-27",
      tipo_de_vehiculo: "Ómnibus Transporte de Personal",
      uso: "TRANSPORTE ESPECIAL DE PERSONAS – TRABAJADORES",
    },
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "SCANIA",
      modelo: "K124IB8X2NB380",
      placa: "T3Q962",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "11000.00",
      moneda: "SOL",
      total: "11000.00",
      fecha_de_adquisicion: "2019-09-13",
      tipo_de_vehiculo: "Ómnibus Transporte Interprovincial",
      uso: "TRANSPORTE REGULAR DE PERSONAS",
    },
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "MERCEDES BENZ",
      modelo: "O-500 RSD 2436/30",
      placa: "D1B952",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "75000.00",
      moneda: "USD",
      total: "75000.00",
      fecha_de_adquisicion: "2025-02-11",
      tipo_de_vehiculo: "Ómnibus Transporte Interprovincial",
      uso: "TRANSPORTE REGULAR DE PERSONAS",
    },
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "MERCEDES BENZ",
      modelo: "O-500 RSD 2436/30",
      placa: "B7C965",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "180810.00",
      moneda: "SOL",
      total: "180810.00",
      fecha_de_adquisicion: "2025-02-20",
      tipo_de_vehiculo: "Ómnibus Transporte Interprovincial",
      uso: "TRANSPORTE REGULAR DE PERSONAS",
    },
    {
      company_id: empresa.id,
      descripcion: "BUS",
      marca: "AGRALE",
      modelo: "MA 17.0",
      placa: "D5Y-957",
      modalidad_de_compra: "FINANCIADO",
      tipo_propiedad: "PROPIO",
      importe: "42000.00",
      moneda: "USD",
      total: "42000.00",
      fecha_de_adquisicion: "1905-07-16",
      tipo_de_vehiculo: "Ómnibus Transporte de Personal",
      uso: "TRANSPORTE ESPECIAL DE PERSONAS – TRABAJADORES",
    },

    // 🔵 CAMIONES (LEASING)
    {
      company_id: empresa.id,
      descripcion: "CAMION BARANDA",
      marca: "HYUNDAI",
      modelo: "EX8",
      placa: "TFL-901",
      modalidad_de_compra: "LEASING",
      tipo_propiedad: "ALQUILADO",
      importe: "34490.00",
      moneda: "USD",
      importe_mejora: "6550.00",
      total: "41040.00",
      fecha_de_adquisicion: "2025-08-27",
      tipo_de_vehiculo: "Camion de Carga",
    },
    {
      company_id: empresa.id,
      descripcion: "CAMION BARANDA",
      marca: "HYUNDAI",
      modelo: "EX8",
      placa: "TFM-833",
      modalidad_de_compra: "LEASING",
      tipo_propiedad: "ALQUILADO",
      importe: "34490.00",
      moneda: "USD",
      importe_mejora: "6550.00",
      total: "41040.00",
      fecha_de_adquisicion: "2025-08-27",
      tipo_de_vehiculo: "Camion de Carga",
    },
    {
      company_id: empresa.id,
      descripcion: "CAMION BARANDA",
      marca: "HYUNDAI",
      modelo: "EX8",
      placa: "TFM-911",
      modalidad_de_compra: "LEASING",
      tipo_propiedad: "ALQUILADO",
      importe: "34490.00",
      moneda: "USD",
      importe_mejora: "6550.00",
      total: "41040.00",
      fecha_de_adquisicion: "2025-08-27",
      tipo_de_vehiculo: "Camion de Carga",
    },
    {
      company_id: empresa.id,
      descripcion: "CAMION BARANDA",
      marca: "HYUNDAI",
      modelo: "EX8",
      placa: "TFM-913",
      modalidad_de_compra: "LEASING",
      tipo_propiedad: "ALQUILADO",
      importe: "34490.00",
      moneda: "USD",
      importe_mejora: "6550.00",
      total: "41040.00",
      fecha_de_adquisicion: "2025-08-27",
      tipo_de_vehiculo: "Camion de Carga",
    },
    {
      company_id: empresa.id,
      descripcion: "CAMION BARANDA",
      marca: "HYUNDAI",
      modelo: "EX8",
      placa: "TFL-935",
      modalidad_de_compra: "LEASING",
      tipo_propiedad: "ALQUILADO",
      importe: "34490.00",
      moneda: "USD",
      importe_mejora: "6550.00",
      total: "41040.00",
      fecha_de_adquisicion: "2025-08-27",
      tipo_de_vehiculo: "Camion de Carga",
    },
    {
      company_id: empresa.id,
      descripcion: "CAMION BARANDA",
      marca: "HYUNDAI",
      modelo: "EX8",
      placa: "TFL-944",
      modalidad_de_compra: "LEASING",
      tipo_propiedad: "ALQUILADO",
      importe: "34490.00",
      moneda: "USD",
      importe_mejora: "6550.00",
      total: "41040.00",
      fecha_de_adquisicion: "2025-08-27",
      tipo_de_vehiculo: "Camion de Carga",
    },
    {
      company_id: empresa.id,
      descripcion: "CAMION BARANDA",
      marca: "HYUNDAI",
      modelo: "EX8",
      placa: "TFL-915",
      modalidad_de_compra: "LEASING",
      tipo_propiedad: "ALQUILADO",
      importe: "34490.00",
      moneda: "USD",
      importe_mejora: "6550.00",
      total: "41040.00",
      fecha_de_adquisicion: "2025-08-27",
      tipo_de_vehiculo: "Camion de Carga",
    },
    {
      company_id: empresa.id,
      descripcion: "CAMION BARANDA",
      marca: "HYUNDAI",
      modelo: "EX8",
      placa: "TFL-943",
      modalidad_de_compra: "LEASING",
      tipo_propiedad: "ALQUILADO",
      importe: "34490.00",
      moneda: "USD",
      importe_mejora: "6550.00",
      total: "41040.00",
      fecha_de_adquisicion: "2025-08-27",
      tipo_de_vehiculo: "Camion de Carga",
    },
    {
      company_id: empresa.id,
      descripcion: "CAMION BARANDA",
      marca: "HYUNDAI",
      modelo: "EX8",
      placa: "TFL-914",
      modalidad_de_compra: "LEASING",
      tipo_propiedad: "ALQUILADO",
      importe: "34490.00",
      moneda: "USD",
      importe_mejora: "6550.00",
      total: "41040.00",
      fecha_de_adquisicion: "2025-08-27",
      tipo_de_vehiculo: "Camion de Carga",
    },
    {
      company_id: empresa.id,
      descripcion: "CAMION BARANDA",
      marca: "HYUNDAI",
      modelo: "EX8",
      placa: "TFM-832",
      modalidad_de_compra: "LEASING",
      tipo_propiedad: "ALQUILADO",
      importe: "34490.00",
      moneda: "USD",
      importe_mejora: "6550.00",
      total: "41040.00",
      fecha_de_adquisicion: "2025-08-27",
      tipo_de_vehiculo: "Camion de Carga",
    },
  ];
  // 3. Insertar
  await db.insert(vehicles).values(data);

  console.log("🔥 Vehículos insertados correctamente");
}

main();
